=== goodlittlescript/goodlittlescript.github.io/series/v0/series.schema.json
{
  "$id": "https://goodlittlescript.github.io/series/v0/series.schema.json",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "description": "A series definition",
  "type": "object",
  "properties": {
    "apiVersion": {
      "type": "string"
    },
    "kind": {
      "type": "string"
    },
    "metadata": {
      "type": "object"
    },
    "spec": {
      "anyOf": [
        { "$ref": "https://goodlittlescript.github.io/series/v0/line-spec.schema.json" },
        { "$ref": "https://goodlittlescript.github.io/series/v0/step-spec.schema.json" },
        { "$ref": "https://goodlittlescript.github.io/series/v0/string-spec.schema.json" }
      ]
    },
    "inputs": {
      "type": "array",
      "items": {
        "type": "array"
      }
    },
    "outputs": {
      "type": "array",
      "items": {
        "type": "array"
      }
    }
  },
  "required": [ "apiVersion", "kind" ],
  "additionalProperties": false
}

=== goodlittlescript/goodlittlescript.github.io/series/v0/line/inputs.json
{
  "apiVersion": "goodlittlescript.github.io/series/v0",
  "inputs": [
    [
      0
    ],
    [
      1
    ]
  ],
  "kind": "Line",
  "outputs": [
    [
      0,
      1
    ],
    [
      1,
      3
    ],
    [
      2,
      5
    ],
    [
      3,
      7
    ],
    [
      4,
      9
    ],
    [
      5,
      11
    ],
    [
      6,
      13
    ],
    [
      7,
      15
    ],
    [
      8,
      17
    ],
    [
      9,
      19
    ]
  ],
  "spec": {
    "b": 1,
    "m": 2,
    "x": {
      "num": 5,
      "start": 0,
      "step": 1
    }
  }
}

=== goodlittlescript/goodlittlescript.github.io/docs/data/kubernetes/label.json
{
  "apiVersion": "goodlittlescript.github.io/series/v0",
  "kind": "String",
  "metadata": {
    "name": "kubernetes.name",
    "references": [
      {
        "notes": [
          "Some resource types require their names to follow the DNS label standard as defined in RFC 1123. This means the name must:\n\n- contain at most 63 characters\n- contain only lowercase alphanumeric characters or '-'\n- start with an alphanumeric character\n- end with an alphanumeric character"
        ],
        "url": "https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#dns-label-names"
      }
    ]
  },
  "spec": {
    "case": "lower",
    "charset": [
      "alnum",
      "-",
      "."
    ],
    "max": 63,
    "min": 1,
    "patterns": [
      {
        "name": "typical",
        "regexp": "[a-z0-9][a-z0-9.-]*[a-z0-9]{1,21}"
      },
      {
        "name": "valid",
        "regexp": "[a-z0-9]([a-z0-9.-]*[a-z0-9])?{1,63}"
      }
    ],
    "sep": "-"
  }
}

=== goodlittlescript/goodlittlescript.github.io/docs/data/kubernetes/name.json
{
  "apiVersion": "goodlittlescript.github.io/series/v0",
  "kind": "String",
  "metadata": {
    "name": "kubernetes.name",
    "references": [
      {
        "notes": [
          "Most resource types require a name that can be used as a DNS subdomain name as defined in RFC 1123. This means the name must:\n\n- contain no more than 253 characters\n- contain only lowercase alphanumeric characters, '-' or '.'\n- start with an alphanumeric character\n- end with an alphanumeric character"
        ],
        "url": "https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#dns-subdomain-names"
      }
    ]
  },
  "spec": {
    "case": "lower",
    "charset": [
      "alnum",
      "-",
      "."
    ],
    "max": 253,
    "min": 1,
    "patterns": [
      {
        "name": "typical",
        "regexp": "[a-z0-9][a-z0-9.-]*[a-z0-9]{1,21}"
      },
      {
        "name": "valid",
        "regexp": "[a-z0-9]([a-z0-9.-]*[a-z0-9])?{1,253}"
      }
    ],
    "sep": "-"
  }
}

=== goodlittlescript/goodlittlescript.github.io/docs/data/postgres/password.json
{
  "apiVersion": "goodlittlescript.github.io/series/v0",
  "kind": "String",
  "metadata": {
    "name": "postgres.password",
    "references": [
      {
        "notes": [
          "postgresql://[user[:password]@][netloc][:port][,...][/dbname][?param1=value1&...]",
          "Percent-encoding may be used to include symbols with special meaning in any of the URI parts, e.g. replace = with %3D."
        ],
        "url": "https://www.postgresql.org/docs/current/libpq-connect.html"
      }
    ]
  },
  "spec": {
    "charset": [
      "print"
    ],
    "max": 30,
    "min": 20,
    "patterns": [
      {
        "name": "typical",
        "regexp": ".{20,30}"
      }
    ]
  }
}
